[package]
name = "i3status-rs"
description = "A feature-rich and resource-friendly replacement for i3status, written in Rust."
repository = "https://github.com/greshake/i3status-rust/"
readme = "README.md"
license = "GPL-3.0-only"
version = "0.30.2"
authors = [
  "Kai Greshake <development@kai-greshake.de>",
  "Contributors on GitHub (https://github.com/greshake/i3status-rust/graphs/contributors)",
]
edition = "2021"
[features]
default = ["pulseaudio"]
pulseaudio = ["libpulse-binding"]
debug_borders = []                # Make widgets' borders visible

[dependencies]
async-once-cell = "0.4"
async-trait = "0.1"
crossbeam-channel = "0.5"
dirs = "4.0"
env_logger = "0.10"
hyper = "0.14"
inotify = "0.10"
libc = "0.2"
libpulse-binding = { version = "2.0", default-features = false, optional = true }
log = "0.4"
maildir = { version = "0.6", optional = true }
neli = { version = "0.6", features = ["async"] }
neli-wifi = { version = "0.4", features = ["async"] }
nix = "0.26"
nom = "7.1.2"
notmuch = { version = "0.8", optional = true }
once_cell = "1"
regex = "1.5"
sensors = "0.2.2"
serde_json = "1.0"
shellexpand = "3.0"
signal-hook = "0.3"
smart-default = "0.6"
swayipc-async = "2.0"
tokio-stream = "0.1"
toml = "0.6"
zbus = { version = "3.8", default-features = false, features = ["tokio"] }
wayrs-client = { version = "0.3", features = ["tokio"] }
wayrs-protocols = { version = "0.3", features = ["wlr-foreign-toplevel-management-unstable-v1"] }

[dependencies.clap]
version = "4.0"
default-features = false
features = ["std", "derive"]

[dependencies.serde]
version = "1.0"
features = ["derive", "rc"]

[dependencies.tokio]
version = "1.12"
features = [
  "fs",
  #"io-util",
  "io-std",
  "macros",
  #"net",
  #"parking_lot",
  "process",
  "rt",
  "rt-multi-thread",
  #"signal",
  "sync",
  "time",
]

[dependencies.futures]
version = "0.3"
default-features = false

[dependencies.chrono]
version = "0.4"
default-features = false
features = ["clock", "unstable-locales"]

[dependencies.chrono-tz]
version = "0.8"
features = ["serde"]

[dependencies.signal-hook-tokio]
version = "0.3"
features = ["futures-v0_3"]

[dependencies.reqwest]
version = "0.11"
features = ["json"]

# Test async code
[dev-dependencies]
tokio-test = "*"

[profile.release]
lto = "thin"
strip = true
debug = 1
[package.metadata.deb]
name = "i3status-rust"
extended-description = """\
Provides provides a way to display 'blocks' of system information (time, \
battery status, volume, etc) on the i3 (https://i3wm.org/) bar.
.
Also compatible with Sway (http://swaywm.org/).
.
For a list of available blocks, see the block documentation in \
usr/share/doc/i3status-rust/blocks.md."""
license-file = ["LICENSE", "0"]
depends = "$auto, libdbus-1-3 (>=1.6), libpulse0"
section = "utils"
priority = "optional"
assets = [
    ["target/release/i3status-rs", "/usr/bin/", "755"],
    ["README.md", "/usr/share/doc/i3status-rust/README", "644"],
    ["doc/blocks.md", "/usr/share/doc/i3status-rust/blocks.md", "644"],
    ["files/icons/*", "/usr/share/i3status-rust/icons/", "644"],
    ["files/themes/*", "/usr/share/i3status-rust/themes/", "644"],
]  
